[package]
name = "idecode"
version = "0.1.0"
description = "Mini IDE modular para aprender a programar"
authors = ["Eduardo Nacimiento-García <enacimie@ull.edu.es>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/enacimie/ideCode"
homepage = "https://github.com/enacimie/ideCode"
readme = "../README.md"
edition = "2021"
default-run = "idecode"

[lib]
name = "idecode_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
walkdir = "2"
tree-sitter = "0.27"
tree-sitter-java = "0.23"
tree-sitter-python = "0.23"
tree-sitter-kotlin-ng = "1.1"
include_dir = "0.7.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
